'use strict';

/**
 * Unit tests for adapters/install-global.js pure helpers.
 *
 * Module-level state (USE_COPY, DO_CURSOR, DO_CLAUDE, HOME, REPO) is captured
 * at require-time, so the larger install* functions are tested via subprocess
 * with a fake HOME (set via env). The pure helpers below are tested directly.
 */

const { describe, it, before, after } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const path = require('path');
const os = require('os');
const { spawnSync } = require('node:child_process');

const {
  REPO,
  PREFIX,
  LOOPS_MARKER,
  isSymlink,
  readLinkSafe,
  resolveMaybe,
  isManagedTarget,
  linkOrCopy,
  isManagedClaudeSkillDir,
  rewriteSkillName,
  buildAwarenessBody,
  listLoopNames,
} = require('../adapters/install-global.js');

describe('install-global.js: link/copy primitives', () => {
  let tmp;
  before(() => {
    tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'ig-prim-'));
  });
  after(() => fs.rmSync(tmp, { recursive: true, force: true }));

  describe('isSymlink / readLinkSafe / resolveMaybe', () => {
    it('isSymlink returns true for symlinks, false for real files/dirs', () => {
      const f = path.join(tmp, 'file');
      fs.writeFileSync(f, 'x');
      const l = path.join(tmp, 'link');
      fs.symlinkSync(f, l);
      assert.equal(isSymlink(f), false);
      assert.equal(isSymlink(l), true);
    });

    it('isSymlink returns false for missing paths (no throw)', () => {
      assert.equal(isSymlink(path.join(tmp, 'nope')), false);
    });

    it('readLinkSafe returns link target for symlinks, null for non-symlinks', () => {
      const f = path.join(tmp, 'rfile');
      fs.writeFileSync(f, 'x');
      const l = path.join(tmp, 'rlink');
      fs.symlinkSync(f, l);
      assert.equal(readLinkSafe(l), f);
      assert.equal(readLinkSafe(f), null);
    });

    it('resolveMaybe returns realpath when possible, else path.resolve', () => {
      const f = path.join(tmp, 'rvfile');
      fs.writeFileSync(f, 'x');
      assert.equal(resolveMaybe(f), fs.realpathSync(f));
      assert.equal(resolveMaybe(path.join(tmp, 'never')), path.resolve(path.join(tmp, 'never')));
    });
  });

  describe('isManagedTarget', () => {
    it('returns true when target is missing', () => {
      assert.equal(isManagedTarget(path.join(tmp, 'missing'), '/anywhere'), true);
    });
    it('returns false for an existing real file (unmanaged)', () => {
      const f = path.join(tmp, 'real');
      fs.writeFileSync(f, 'x');
      assert.equal(isManagedTarget(f, '/anywhere'), false);
    });
    it('returns true when symlink resolves to expected target', () => {
      const target = path.join(tmp, 'expected');
      fs.writeFileSync(target, 'x');
      const l = path.join(tmp, 'sym');
      fs.symlinkSync(target, l);
      assert.equal(isManagedTarget(l, target), true);
    });
    it('returns false when symlink resolves to a different target', () => {
      const a = path.join(tmp, 'a');
      const b = path.join(tmp, 'b');
      fs.writeFileSync(a, 'x');
      fs.writeFileSync(b, 'x');
      const l = path.join(tmp, 'wrong');
      fs.symlinkSync(a, l);
      assert.equal(isManagedTarget(l, b), false);
    });
  });

  describe('isManagedClaudeSkillDir', () => {
    it('returns true when target is missing', () => {
      assert.equal(isManagedClaudeSkillDir(path.join(tmp, 'missing'), 'loops-x'), true);
    });
    it('returns true when SKILL.md has the prefixed name', () => {
      const d = path.join(tmp, 'good');
      fs.mkdirSync(d);
      fs.writeFileSync(path.join(d, 'SKILL.md'), '---\nname: loops-x\n---\n');
      assert.equal(isManagedClaudeSkillDir(d, 'loops-x'), true);
    });
    it('returns true when SKILL.md has the loops-marker', () => {
      const d = path.join(tmp, 'marker');
      fs.mkdirSync(d);
      fs.writeFileSync(path.join(d, 'SKILL.md'), `<!-- loops-global-install -->\n---\nname: x\n---\n`);
      assert.equal(isManagedClaudeSkillDir(d, 'loops-x'), true);
    });
    it('returns true when SKILL.md has the "Auto-generated by loops" comment', () => {
      const d = path.join(tmp, 'gen');
      fs.mkdirSync(d);
      fs.writeFileSync(path.join(d, 'SKILL.md'), '<!-- Auto-generated by loops/emit.js -->\n');
      assert.equal(isManagedClaudeSkillDir(d, 'loops-x'), true);
    });
    it('returns false for an unowned skill directory', () => {
      const d = path.join(tmp, 'unowned');
      fs.mkdirSync(d);
      fs.writeFileSync(path.join(d, 'SKILL.md'), '---\nname: someone-elses-skill\n---\n');
      assert.equal(isManagedClaudeSkillDir(d, 'loops-x'), false);
    });
    it('returns false when SKILL.md is missing', () => {
      const d = path.join(tmp, 'noyaml');
      fs.mkdirSync(d);
      assert.equal(isManagedClaudeSkillDir(d, 'loops-x'), false);
    });
  });
});

describe('install-global.js: rewriteSkillName', () => {
  it('replaces existing top-level name with the prefixed name', () => {
    const input = '---\nname: sar\ndescription: x\n---\nbody';
    const out = rewriteSkillName(input, 'sar', 'loops-sar');
    assert.match(out, /^name: loops-sar$/m);
  });

  it('inserts name: line when no name exists', () => {
    const input = '---\ndescription: x\n---\nbody';
    const out = rewriteSkillName(input, 'sar', 'loops-sar');
    assert.match(out, /^name: loops-sar$/m);
  });

  it('inserts the loops-marker after the closing --- of frontmatter', () => {
    const input = '---\nname: sar\n---\nbody';
    const out = rewriteSkillName(input, 'sar', 'loops-sar');
    const afterFm = out.split('---\n').slice(2).join('---\n');
    assert.match(afterFm, /<!-- loops-global-install -->/);
  });

  it('does not add a second marker when one is already present', () => {
    const input = `<!-- loops-global-install -->\n---\nname: loops-sar\n---\nbody`;
    const out = rewriteSkillName(input, 'sar', 'loops-sar');
    const matches = out.match(/<!-- loops-global-install -->/g) || [];
    assert.equal(matches.length, 1);
  });

  it('prepends [loops] to description when description lacks loops- prefix', () => {
    const input = '---\nname: sar\ndescription: A spec attack repair workflow.\n---\nbody';
    const out = rewriteSkillName(input, 'sar', 'loops-sar');
    assert.match(out, /description: \[loops\] A spec attack repair workflow\./);
  });

  it('does not double-prefix [loops] when already prefixed', () => {
    const input =
      '---\nname: sar\ndescription: [loops] Already prefixed.\n---\nbody';
    const out = rewriteSkillName(input, 'sar', 'loops-sar');
    assert.match(out, /description: \[loops\] Already prefixed\./);
    assert.doesNotMatch(out, /\[loops\] \[loops\]/);
  });

  it('leaves description alone when it already mentions loops-', () => {
    const input =
      '---\nname: sar\ndescription: Use the loops-sar skill here.\n---\nbody';
    const out = rewriteSkillName(input, 'sar', 'loops-sar');
    assert.doesNotMatch(out, /\[loops\] Use the loops-sar/);
  });
});

describe('install-global.js: buildAwarenessBody', () => {
  it('keeps the frontmatter for Cursor output', () => {
    const body = buildAwarenessBody({ forClaude: false });
    assert.match(body, /^---\n/);
  });

  it('strips the frontmatter for Claude output', () => {
    const body = buildAwarenessBody({ forClaude: true });
    assert.doesNotMatch(body, /^---\n/);
  });

  it('includes the loops-marker for Claude output', () => {
    const body = buildAwarenessBody({ forClaude: true });
    assert.ok(body.startsWith(LOOPS_MARKER + '\n') || body.includes(LOOPS_MARKER));
  });

  it('includes the absolute repo path', () => {
    const body = buildAwarenessBody({ forClaude: false });
    assert.match(body, new RegExp(REPO.replace(/[/.]/g, '\\$&')));
  });

  it('mentions the stable symlink', () => {
    const body = buildAwarenessBody({ forClaude: true });
    assert.match(body, /~\/\.loops/);
  });

  it('is idempotent: re-running does not duplicate the Installed paths section', () => {
    const first = buildAwarenessBody({ forClaude: false });
    const second = buildAwarenessBody({ forClaude: false });
    const matches1 = (first.match(/## Installed paths/g) || []).length;
    const matches2 = (second.match(/## Installed paths/g) || []).length;
    assert.equal(matches1, 1, `first had ${matches1} sections`);
    assert.equal(matches2, 1, `second had ${matches2} sections`);
  });
});

describe('install-global.js: listLoopNames', () => {
  it('returns a sorted list of names (dispatcher is in the list, not necessarily first)', () => {
    // listLoopNames prepends 'dispatcher' then sorts the full list. Because
    // 'adversarial-gate' < 'dispatcher' alphabetically, dispatcher is rarely
    // at index 0 in the result. Verify shape + membership instead.
    const names = listLoopNames();
    assert.ok(Array.isArray(names));
    assert.ok(names.includes('dispatcher'), 'dispatcher must be in the list');
    const sorted = [...names].sort();
    assert.deepEqual(names, sorted, 'list should be sorted');
  });

  it('has no duplicates', () => {
    const names = listLoopNames();
    assert.equal(new Set(names).size, names.length);
  });

  it('returns sorted loop names from the repo', () => {
    const names = listLoopNames();
    const sorted = [...names].sort();
    assert.deepEqual(names, sorted);
  });

  it('includes at least the 9 catalog loops', () => {
    const names = new Set(listLoopNames());
    for (const expected of [
      'plan-and-implement',
      'tdd',
      'sar',
      'adversarial-gate',
      'reproduce-and-fix',
      'migrate',
      'explain-codebase',
      'swarm',
      'use-the-loop',
    ]) {
      assert.ok(names.has(expected), `missing: ${expected}`);
    }
  });
});

describe('install-global.js: CLI integration (subprocess, fake HOME)', () => {
  // The full install touches ~/.claude, ~/.cursor, ~/.loops. We use a fake
  // HOME so we never touch the user's real config. This is the safest way
  // to exercise the install loop end-to-end.

  function run(args, { home, dryRun = false } = {}) {
    const env = { ...process.env, HOME: home };
    const allArgs = [...args];
    if (dryRun) allArgs.push('--dry-run');
    return spawnSync(
      process.execPath,
      [path.join(REPO, 'adapters', 'install-global.js'), ...allArgs],
      { env, encoding: 'utf8' }
    );
  }

  it('--help exits 0 and prints usage', () => {
    const r = run(['--help'], { home: os.tmpdir() });
    assert.equal(r.status, 0);
    assert.match(r.stdout, /Usage:/);
  });

  it('--dry-run --no-emit does not create user files in HOME (only scratch dirs)', () => {
    // KNOWN SIDE EFFECT: installClaudeSkills() in --dry-run still calls
    // ensureDir(CLAUDE_SKILLS), which creates ~/.claude/skills/ as an empty
    // directory even though no skill files are written. The test asserts the
    // realistic contract: no real skill/rule files end up under HOME, and no
    // ~/.loops symlink is created.
    const home = fs.mkdtempSync(path.join(os.tmpdir(), 'ig-home-'));
    try {
      const r = run(['--dry-run', '--no-emit'], { home });
      assert.equal(r.status, 0, r.stderr + r.stdout);
      assert.match(r.stdout, /dry-run/);
      // The .loops symlink is never created in dry-run.
      assert.equal(fs.existsSync(path.join(home, '.loops')), false);
      // No Cursor awareness rule written.
      assert.equal(
        fs.existsSync(path.join(home, '.cursor', 'rules', 'loops.mdc')),
        false
      );
      // No Claude awareness rule written.
      assert.equal(
        fs.existsSync(path.join(home, '.claude', 'rules', 'loops.md')),
        false
      );
      // No real (non-empty) Claude skill dirs.
      if (fs.existsSync(path.join(home, '.claude', 'skills'))) {
        const skills = fs.readdirSync(path.join(home, '.claude', 'skills'));
        for (const s of skills) {
          const sd = path.join(home, '.claude', 'skills', s);
          if (fs.statSync(sd).isDirectory()) {
            const contents = fs.readdirSync(sd);
            assert.equal(contents.length, 0, `skill ${s} should be empty in dry-run`);
          }
        }
      }
    } finally {
      fs.rmSync(home, { recursive: true, force: true });
    }
  });

  it('--uninstall on a clean home is a no-op (exits 0)', () => {
    const home = fs.mkdtempSync(path.join(os.tmpdir(), 'ig-home-clean-'));
    try {
      const r = run(['--uninstall'], { home });
      assert.equal(r.status, 0, r.stderr + r.stdout);
    } finally {
      fs.rmSync(home, { recursive: true, force: true });
    }
  });

  it('--uninstall --dry-run is a no-op', () => {
    const home = fs.mkdtempSync(path.join(os.tmpdir(), 'ig-home-dry-un-'));
    try {
      const r = run(['--uninstall', '--dry-run'], { home });
      assert.equal(r.status, 0, r.stderr + r.stdout);
      assert.match(r.stdout, /dry-run/);
    } finally {
      fs.rmSync(home, { recursive: true, force: true });
    }
  });

  it('exits non-zero when both --cursor-only and --claude-only are passed', () => {
    const home = fs.mkdtempSync(path.join(os.tmpdir(), 'ig-home-both-'));
    try {
      const r = run(['--cursor-only', '--claude-only'], { home });
      assert.notEqual(r.status, 0);
      assert.match(r.stderr, /only one of/);
    } finally {
      fs.rmSync(home, { recursive: true, force: true });
    }
  });

  it('--copy + --no-emit + --dry-run is safe (no real writes)', () => {
    const home = fs.mkdtempSync(path.join(os.tmpdir(), 'ig-home-copy-'));
    try {
      const r = run(['--copy', '--no-emit', '--dry-run'], { home });
      assert.equal(r.status, 0, r.stderr + r.stdout);
      // dry-run should not have created anything in HOME
      assert.equal(fs.existsSync(path.join(home, '.loops')), false);
    } finally {
      fs.rmSync(home, { recursive: true, force: true });
    }
  });
});
