#!/usr/bin/env node
/**
 * Adapters: emit platform-specific files from canonical loop.md + loop.yaml.
 *
 * Usage:
 *   node adapters/emit.js           # emit for all loops
 *   node adapters/emit.js <loop>    # emit for one loop
 *
 * Outputs:
 *   .cursor/rules/<loop>.mdc
 *   .claude/skills/<loop>/SKILL.md
 *   .claude/skills/<loop>/loop.yaml
 *   .claude/skills/dispatcher/SKILL.md
 *   .claude/skills/dispatcher/loop.yaml
 */

const fs = require('fs');
const path = require('path');

const REPO = path.resolve(__dirname, '..');

function readLoopYaml(dir) {
  const p = path.join(dir, 'loop.yaml');
  if (!fs.existsSync(p)) return null;
  return fs.readFileSync(p, 'utf8');
}

function emitCursor(loopName, canonicalPath) {
  const src = fs.readFileSync(canonicalPath, 'utf8');
  // The .mdc file is the canonical loop.md with a tiny YAML frontmatter
  // wrapper that Cursor expects. We strip the canonical # heading and let
  // the frontmatter title be the source of truth.
  const body = src.replace(/^# .+\n/, '');
  const out = path.join(REPO, '.cursor', 'rules', `${loopName}.mdc`);
  fs.mkdirSync(path.dirname(out), { recursive: true });
  const frontmatter = [
    '---',
    `description: Auto-generated by loops/emit.js from ${path.relative(REPO, canonicalPath)}`,
    'globs:',
    'alwaysApply: false',
    '---',
    '',
  ].join('\n');
  fs.writeFileSync(out, frontmatter + body);
  console.log(`  cursor: ${path.relative(REPO, out)}`);
}

function emitClaudeSkill(loopName, canonicalDir) {
  const md = fs.readFileSync(path.join(canonicalDir, 'loop.md'), 'utf8');
  const yaml = readLoopYaml(canonicalDir);
  const outDir = path.join(REPO, '.claude', 'skills', loopName);
  fs.mkdirSync(outDir, { recursive: true });
  // Claude Code skills use YAML frontmatter: name, description
  const fm = [
    '---',
    `name: ${loopName}`,
    `description: ${extractDescription(yaml) || `Loops loop: ${loopName}`}`,
    '---',
    '',
  ].join('\n');
  fs.writeFileSync(path.join(outDir, 'SKILL.md'), fm + md);
  if (yaml) {
    fs.writeFileSync(path.join(outDir, 'loop.yaml'), yaml);
  }
  console.log(`  claude: ${path.relative(REPO, outDir)}/`);
}

function extractDescription(yamlText) {
  if (!yamlText) return null;
  // Accept 2+ spaces of indent (YAML block scalars often use 2 spaces).
  const m = yamlText.match(/^description:\s*\|?\s*\n((?:\s{2,}.+\n?)+)/m);
  if (m) return m[1].trim().split('\n')[0];
  const m2 = yamlText.match(/^description:\s*(.+)$/m);
  return m2 ? m2[1].trim().replace(/^['"]|['"]$/g, '') : null;
}

function emitAll(target) {
  const dirs = [
    ['dispatcher', path.join(REPO, 'dispatcher')],
    ...fs
      .readdirSync(path.join(REPO, 'loops'))
      .filter((n) => fs.statSync(path.join(REPO, 'loops', n)).isDirectory())
      .map((n) => [n, path.join(REPO, 'loops', n)]),
  ];

  for (const [name, dir] of dirs) {
    if (target && name !== target) continue;
    const canonical = path.join(dir, 'loop.md');
    if (!fs.existsSync(canonical)) {
      console.warn(`skip ${name}: no loop.md`);
      continue;
    }
    console.log(`emit ${name}:`);
    emitCursor(name, canonical);
    emitClaudeSkill(name, dir);
  }
}

const target = process.argv[2];
emitAll(target);
console.log('done.');
