#!/usr/bin/env node
/**
 * Adapters: emit platform-specific files from canonical loop.md + loop.yaml.
 *
 * Usage:
 *   node adapters/emit.js              # emit for all loops
 *   node adapters/emit.js <loop>       # emit for one loop
 *   node adapters/emit.js --check      # exit 1 if emit would change files
 *   node adapters/emit.js --help
 *
 * Outputs (namespaced with loops- to avoid skill collisions):
 *   <out>/.cursor/rules/loops-<loop>.mdc
 *   <out>/.claude/skills/loops-<loop>/SKILL.md
 *   <out>/.claude/skills/loops-<loop>/loop.yaml
 *
 * Out root: this repo normally. If this repo is cloned as `.loops/` inside
 * another project, emit writes into that project root instead.
 */

const fs = require('fs');
const path = require('path');
const os = require('os');

const REPO = path.resolve(__dirname, '..');
const PREFIX = 'loops-';
const VALID_MODEL_CLASSES = new Set(['high-reasoning', 'workhorse', 'cheap-fast']);

const args = process.argv.slice(2);
const CHECK = args.includes('--check');
const HELP = args.includes('--help') || args.includes('-h');
const target = args.find((a) => !a.startsWith('-')) || null;

function die(msg) {
  console.error(`error: ${msg}`);
  process.exit(1);
}

function printHelp() {
  console.log(`Usage: node adapters/emit.js [loop] [--check] [--help]

Emit Cursor rules + Claude skills from canonical loop.md / loop.yaml.

  (no args)     Emit all loops + dispatcher
  <loop>        Emit one loop (or "dispatcher")
  --check       Write to a temp dir and fail if committed emit output differs
  --help        Show this help

Out root: ${resolveOutRoot()}
Prefix:   ${PREFIX}<name>
`);
}

/** When repo lives at project/.loops, emit into the project. */
function resolveOutRoot() {
  if (path.basename(REPO) === '.loops') {
    return path.dirname(REPO);
  }
  return REPO;
}

function listLoopDirs() {
  const dirs = [['dispatcher', path.join(REPO, 'dispatcher')]];
  const loopsDir = path.join(REPO, 'loops');
  for (const n of fs.readdirSync(loopsDir).sort()) {
    const d = path.join(loopsDir, n);
    if (fs.statSync(d).isDirectory()) dirs.push([n, d]);
  }
  return dirs;
}

function readLoopYaml(dir) {
  const p = path.join(dir, 'loop.yaml');
  if (!fs.existsSync(p)) return null;
  return fs.readFileSync(p, 'utf8');
}

/** Join block-scalar description lines; fall back to single-line description. */
function extractDescription(yamlText) {
  if (!yamlText) return null;
  const block = yamlText.match(/^description:\s*\|\s*\n((?:\s{2,}.+\n?)+)/m);
  if (block) {
    const joined = block[1]
      .split('\n')
      .map((l) => l.replace(/^\s{2,}/, '').trim())
      .filter(Boolean)
      .join(' ')
      .replace(/\s+/g, ' ')
      .trim();
    // Claude skill descriptions should stay reasonably short.
    return joined.length > 280 ? `${joined.slice(0, 277)}...` : joined;
  }
  const m2 = yamlText.match(/^description:\s*(.+)$/m);
  return m2 ? m2[1].trim().replace(/^['"]|['"]$/g, '') : null;
}

function yamlField(yamlText, field) {
  const m = yamlText.match(new RegExp(`^${field}:\\s*(.+)$`, 'm'));
  return m ? m[1].trim().replace(/^['"]|['"]$/g, '') : null;
}

function validateLoop(name, dir, yamlText) {
  const errors = [];
  if (!yamlText) {
    errors.push(`${name}: missing loop.yaml`);
    return errors;
  }
  const yamlName = yamlField(yamlText, 'name');
  if (yamlName && yamlName !== name) {
    errors.push(`${name}: loop.yaml name "${yamlName}" !== directory "${name}"`);
  }
  const version = yamlField(yamlText, 'version');
  if (!version) errors.push(`${name}: loop.yaml missing version`);

  if (name === 'dispatcher') {
    const mc = yamlField(yamlText, 'model_class');
    if (mc && !VALID_MODEL_CLASSES.has(mc)) {
      errors.push(`${name}: invalid model_class "${mc}"`);
    }
    return errors;
  }

  const phaseBlocks = yamlText.match(/^\s+- name:\s*(.+)$/gm) || [];
  if (phaseBlocks.length === 0) {
    errors.push(`${name}: no phases[] in loop.yaml`);
  }
  const classMatches = yamlText.match(/^\s+model_class:\s*(.+)$/gm) || [];
  for (const line of classMatches) {
    const mc = line.replace(/^\s+model_class:\s*/, '').trim();
    if (!VALID_MODEL_CLASSES.has(mc)) {
      errors.push(`${name}: invalid model_class "${mc}"`);
    }
  }
  return errors;
}

function buildCursorContent(loopName, canonicalPath) {
  const src = fs.readFileSync(canonicalPath, 'utf8');
  const body = src.replace(/^# .+\n/, '');
  const frontmatter = [
    '---',
    `description: Auto-generated by loops/emit.js from ${path.relative(REPO, canonicalPath)}`,
    'alwaysApply: false',
    '---',
    '',
  ].join('\n');
  return frontmatter + body;
}

function buildClaudeSkillMd(loopName, canonicalDir) {
  const md = fs.readFileSync(path.join(canonicalDir, 'loop.md'), 'utf8');
  const yaml = readLoopYaml(canonicalDir);
  const prefixed = `${PREFIX}${loopName}`;
  const desc = extractDescription(yaml) || `Loops loop: ${loopName}`;
  const fm = [
    '---',
    `name: ${prefixed}`,
    `description: ${desc}`,
    '---',
    '',
  ].join('\n');
  return { skillMd: fm + md, yaml };
}

function writeFile(filePath, content, { dry = false } = {}) {
  if (dry) return;
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content);
}

function pathExists(p) {
  try {
    fs.lstatSync(p);
    return true;
  } catch {
    return false;
  }
}

function removeLegacyUnprefixed(outRoot, name) {
  const legacyRule = path.join(outRoot, '.cursor', 'rules', `${name}.mdc`);
  const legacySkill = path.join(outRoot, '.claude', 'skills', name);
  for (const p of [legacyRule, legacySkill]) {
    if (!pathExists(p)) continue;
    fs.rmSync(p, { recursive: true, force: true });
    console.log(`  removed legacy: ${path.relative(outRoot, p)}`);
  }
}

function emitOne(name, dir, outRoot, { dry = false } = {}) {
  const canonical = path.join(dir, 'loop.md');
  if (!fs.existsSync(canonical)) {
    console.warn(`skip ${name}: no loop.md`);
    return { name, skipped: true };
  }

  const yamlText = readLoopYaml(dir);
  const errors = validateLoop(name, dir, yamlText);
  if (errors.length) {
    for (const e of errors) console.error(`  validate: ${e}`);
    die(`validation failed for ${name}`);
  }

  const prefixed = `${PREFIX}${name}`;
  const rulePath = path.join(outRoot, '.cursor', 'rules', `${prefixed}.mdc`);
  const skillDir = path.join(outRoot, '.claude', 'skills', prefixed);
  const skillMdPath = path.join(skillDir, 'SKILL.md');
  const skillYamlPath = path.join(skillDir, 'loop.yaml');

  const cursorContent = buildCursorContent(name, canonical);
  const { skillMd, yaml } = buildClaudeSkillMd(name, dir);

  if (!dry) {
    removeLegacyUnprefixed(outRoot, name);
    writeFile(rulePath, cursorContent);
    writeFile(skillMdPath, skillMd);
    if (yaml) writeFile(skillYamlPath, yaml);
    console.log(`emit ${name}:`);
    console.log(`  cursor: ${path.relative(outRoot, rulePath)}`);
    console.log(`  claude: ${path.relative(outRoot, skillDir)}/`);
  }

  return {
    name,
    files: {
      [rulePath]: cursorContent,
      [skillMdPath]: skillMd,
      ...(yaml ? { [skillYamlPath]: yaml } : {}),
    },
  };
}

function emitAll(outRoot, { dry = false } = {}) {
  const results = [];
  for (const [name, dir] of listLoopDirs()) {
    if (target && name !== target) continue;
    results.push(emitOne(name, dir, outRoot, { dry }));
  }
  return results;
}

function checkMode() {
  const outRoot = resolveOutRoot();
  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'loops-emit-check-'));
  try {
    const results = [];
    for (const [name, dir] of listLoopDirs()) {
      if (target && name !== target) continue;
      results.push(emitOne(name, dir, tmp, { dry: false }));
    }

    const diffs = [];
    for (const r of results) {
      if (r.skipped || !r.files) continue;
      for (const [absInTmp, content] of Object.entries(r.files)) {
        const rel = path.relative(tmp, absInTmp);
        const committed = path.join(outRoot, rel);
        if (!fs.existsSync(committed)) {
          diffs.push(`missing: ${rel}`);
          continue;
        }
        const existing = fs.readFileSync(committed, 'utf8');
        if (existing !== content) {
          diffs.push(`drift: ${rel}`);
        }
      }
    }

    for (const [name] of listLoopDirs()) {
      const legacyRule = path.join(outRoot, '.cursor', 'rules', `${name}.mdc`);
      const legacySkill = path.join(outRoot, '.claude', 'skills', name);
      if (fs.existsSync(legacyRule)) diffs.push(`legacy rule present: .cursor/rules/${name}.mdc`);
      if (fs.existsSync(legacySkill)) diffs.push(`legacy skill present: .claude/skills/${name}/`);
    }

    if (diffs.length) {
      console.error('emit --check FAILED:');
      for (const d of diffs) console.error(`  ${d}`);
      console.error('Fix: node adapters/emit.js && git add .cursor .claude');
      process.exit(1);
    }
    console.log('emit --check OK (no drift).');
  } finally {
    fs.rmSync(tmp, { recursive: true, force: true });
  }
}

function main() {
  if (HELP) {
    printHelp();
    return;
  }
  if (CHECK) {
    checkMode();
    return;
  }
  const outRoot = resolveOutRoot();
  console.log(`out: ${outRoot}`);
  emitAll(outRoot, { dry: false });
  console.log('done.');
}

main();
